services:
  - docker
script:
  - ./bin/build.sh
after_success:
  - ./bin/push.sh
env:
  global:
    # RELEASE contains the serverless release to build
    # Ref: https://github.com/serverless/serverless/releases
    - RELEASE=1.26.1 
    - secure: Q88a8j51jcn82alNszPA3BW9HfgNyIju4yshgfIaIkr1j4ajY+SxCGp5EnbrsMzYRdBBw8ScrwIByMfIfM9XDF3i+DZnPenOzVBjj0+YElb1GBip5ohh8Z4pFoWKbQx+Y81sJ/NDa2eFNEyw4CIZgPSiqA3RJg7+BO1zX9K8gZG46WejJ2pXZhMROdPC9tgi0ZlPPGDDkfu5/ujlSMuMWA8nqzCnWBQ3HpInKXH3pX+i4sJ92qgM3VOX8tNDv+042KJcorrp+6HX1oTXcdKA9rkbHX5X4u0H/Q+VT+t5F/1J28dhdzBIUFUK+53/9J1kpoParQPNzf2Vj1sKy7ECaLqjpOqsJAn1aPz45CxgKFlxW3WPnGreJJAu6tW5aRaSZRZGu/GaSILcynOTVjbTYLISbv+ZZvHwtUoR1UWLGUe9OEOCqDfyhXYAFvOwXI95rN08g/1rV18Cn1MDYt3cUG5h3lS4fjeqm5zVRqgUKS/vCBPmQERsRlr8YPsSV1Bn3qgseDhNbpvWseonBeUoCOMJPq6UDfOiIQQiwgSFl/E4aOu6NkZYvC2beFe0fzmcBsoMjgfb+DeWHm2DwiZgi+LhipW0OmMmw3NoCxuX+H5ThA23TXlQrGKlxHGKYW6QWyTYb5VAdSOQYnGNPyYrWU1F1QmDjcBhncW4p5wbcQQ=
    - secure: Yj+PGHDF+XRw2FJ9apCuSKPp0wV/IbZTxWIoapnLPvqcZ3xLVM07F3BKrUsxG07wsuo9sV84npbYILejaWJlYjZkCBe+htPLt8jPSTT881LBx18q6aLGAS/3aQeOeNLcsUyO10M/PZ026UoLzJI+11grg1BIGG4YKwgf3MN2AN/KhV7Pt+1e8rQPa19qRkGdQWV+80rlHzOFuK95eIfaAL1e/aeyDt0S7K+ZfzgnFv73iTNo/K/6FIfH6MNdlEywBHj5xWucoLApu7Vs7kEIL5etaxw4atiJKsNcGOUY3FlhLQZWph3CJ47liWRwR0Dvq8+xj8W3hWtU5R2Em+Fg1KSKzOVp2/lr53sTddLP1MuhNpGxmGU5NAzwTrIoRqtxId7xDpXEl0UHCkteue88gYKXO7FuhUHhLoYPXtMzn4uggnuJMqk7XIKSdhngM6Z63iq6/M79A+BWtYlYnDP41Tf0ezdF4k0+TpjoeJLbweYofFodUouUl8Yu1FOs3HYEfobxswbr+JojCr/M6oUxehTghi34PZEaXHvzEYVgSZf9D2KS5mJfW4BZ5ZFGv+wbJkNG9bfb0wtZce/t8jII5guxGYdwwrKhIf4EcbJxU7V/p17eM2+3TwH0lameL+t6yWCxUYQ9JIQLT0rCYaKZ+4tYr0PWH5O/9rGbhjKV3AE=
