name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
      env:
        RELEASE: 1.50.0
    - name: Build
      run: ./bin/build.sh
    - name: Push
      run: ./bin/push.sh
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
